---
title: "About"
---

My parents moved to [Qingdao](https://en.wikipedia.org/wiki/Qingdao), the city where I was born and grew up, from rural [Henan](https://en.wikipedia.org/wiki/Henan) in the early 1990s. My elder sister was just born as the time and was left in the village to be taken care by my grandparents.

China was changing rapidly. The country was still figuring out its way forward from decades of chaos and trauma. Transformations of all types were happening before people realised them. My parents were lucky. They made their business fortunes in the city from scratch, also in a way that they probably didn't expect. Thanks to their lucks, and of course more importantly, hard-work and commitments to investing in education (esp. my mother), my sister and I were able to pursue advanced education overseas.

Of course, I personally have no ideas what life and society were like back in the 1990s and earlier, perhaps not even early 2000s. I get most of the impressions from my parents talking about their childhoods (in hunger and search for all sorts of things as snacks, as how most of the times the stories are told) and youth, and reading history. I guess the past is always a mystery, but certainly more so in contemporary China than perhaps anywhere else.

My education trajectory in China was suddenly interrupted by a
